### ISSUE TITLE
Oscilloscope Recording

### ISSUE THREAD

**Issue by iceblu3710** [PetteriAimonen/QuadPawn#19]
I was hoping to use Pawn to make automated recording of transitions as I have a 24V signal that is sparatically noisy. It seems the oscilloscope features are custom on the FPGA though. Is there any way to use Pawn to make my automated recordings?

Essentially I want to run a ring buffer and sample channel A, whenever it transitions across 12V (up and down) to save the buffer to a CSV file. I can then later graph the data and see the transitions quality.

**Comment by PetteriAimonen** [comment]
Yeah, that should be possible.

You probably want a quite high samplerate (>= 1MHz), where Pawn can't process all samples in realtime. Instead you have to use triggering, so that the FPGA will capture samples around the change point and you can then read them out and save.

It's been a while since I've written code for this, but something like this might work:

```
config_chA(ADC_DC, ADC_5V, .offset = 0);
wavein_settrigger(Trig_PosEdge, .channel = Ch_A, .threshold = 128);
wavein_samplerate(1000000);

while (true)
{
  wavein_start();
  new data{3000};
  wavein_read(data); // Waits until FPGA is triggered
  print("Got triggered: first data "); print(str(data[0]));
  print(" last data "); print(str(data[2999])); print("\n");
}
```

For saving CSV, this code could help: https://github.com/PetteriAimonen/QuadPawn/blob/master/Programs/freqresp.pawn#L220

**Comment by iceblu3710** [comment]
This is the first steps that I needed, thanks!
